var airportList = [
    {
        name: 'Toronto Pearson International Airport',
        code: 'YYZ',
        lat: 43.676667,
        long: -79.630556,
        cur: 'CAD',
    },
    {
        name: 'Ottawa International Airport',
        code: 'YOW',
        lat: 45.3225,
        long: -75.667222,
        cur: 'CAD',
    },
    {
        name: 'Vancouver International Airport',
        code: 'YVR',
        lat: 49.194722,
        long: -123.183889,
        cur: 'CAD',
    },
    {
        name: 'Calgary International Airport',
        code: 'YYC',
        lat: 51.1225,
        long: -114.013333,
        cur: 'CAD',
    },
    {
        name: 'Winnipeg International Airport',
        code: 'YWG',
        lat: 49.91,
        long: -97.24,
        cur: 'CAD',
    },
    {
        name: 'Thunder Bay International Airport',
        code: 'YQT',
        lat: 48.371944,
        long: -89.321667,
        cur: 'CAD',
    },
    {
        name: 'Windsor International Airport',
        code: 'YQG',
        lat: 42.276111,
        long: -82.955278,
        cur: 'CAD',
    },
    {
        name: 'Montréal International Airport',
        code: 'YUL',
        lat: 45.470556,
        long: -73.740833,
        cur: 'CAD',
    },
    {
        name: 'Québec International Airport',
        code: 'YQB',
        lat: 46.791111,
        long: -71.393333,
        cur: 'CAD',
    },
    {
        name: 'Nuevo Laredo International Airport',
        code: 'NLD',
        lat: 27.443889,
        long:  -99.570556,
        cur: 'MXN',
    },
    {
        name: 'Piedras Negras International',
        code: 'PDS',
        lat: 28.6275,
        long: -100.535278,
        cur: 'MXN',
    },
    {
        name: 'Ciudad Juarez International',
        code: 'CJS',
        lat: 31.636389,
        long: -106.428611,
        cur: 'MXN',
    },
    {
        name: 'Nogales International Airport',
        code: 'OLS',
        lat: 31.417778,
        long: -110.847778,
        cur: 'MXN',
    },
    {
        name: 'Tijuana International Airport',
        code: 'TIJ',
        lat: 32.540833,
        long: -116.97,
        cur: 'MXN',
    },
    {
        name: 'Matamoros International Airport',
        code: 'MAM',
        lat: 25.77,
        long: -97.525278,
        cur: 'MXN',
    },
]

var safeZone = [
    {
        country: 'New Zealand',
        name: 'Auckland Airport',
        code: 'AKL',
        lat: -37.008056,
        long: 174.791667,
    },
    {
      country: 'Thailand',
      name: 'Suvarnabhumi Airport',
      code: 'BKK',
      lat: 13.6925,
      long: 100.75, 
    },
    {
        country: 'Greenland',
        name: 'Kangerlussuaq Airport',
        code: 'SFJ',
        lat: 67.016944,
        long: -50.689444, 
      },
      {
        country: 'Fiji',
        name: 'Nadi International Airport',
        code: 'NAN',
        lat: -17.755278,
        long: 177.443333, 
      },
      {
        country: 'Cayman Islands',
        name: 'Owen Roberts International Airport',
        code: 'GCM',
        lat: 19.2925,
        long:  -81.359167, 
      },
]

